<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cast_channel.proto

namespace Cast_channel\CastMessage;

use UnexpectedValueException;

/**
 * What type of data do we have in this message.
 *
 * Protobuf type <code>cast_channel.CastMessage.PayloadType</code>
 */
class PayloadType
{
    /**
     * Generated from protobuf enum <code>STRING = 0;</code>
     */
    const STRING = 0;
    /**
     * Generated from protobuf enum <code>BINARY = 1;</code>
     */
    const BINARY = 1;

    private static $valueToName = [
        self::STRING => 'STRING',
        self::BINARY => 'BINARY',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(PayloadType::class, \Cast_channel\CastMessage_PayloadType::class);

