<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cast_channel.proto

namespace Cast_channel\CastMessage;

use UnexpectedValueException;

/**
 * Always pass a version of the protocol for future compatibility
 * requirements.
 *
 * Protobuf type <code>cast_channel.CastMessage.ProtocolVersion</code>
 */
class ProtocolVersion
{
    /**
     * Generated from protobuf enum <code>CASTV2_1_0 = 0;</code>
     */
    const CASTV2_1_0 = 0;

    private static $valueToName = [
        self::CASTV2_1_0 => 'CASTV2_1_0',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ProtocolVersion::class, \Cast_channel\CastMessage_ProtocolVersion::class);

