<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cast_channel.proto

namespace Cast_channel;

if (false) {
    /**
     * This class is deprecated. Use Cast_channel\AuthError\ErrorType instead.
     * @deprecated
     */
    class AuthError_ErrorType {}
}
class_exists(AuthError\ErrorType::class);
@trigger_error('Cast_channel\AuthError_ErrorType is deprecated and will be removed in the next major release. Use Cast_channel\AuthError\ErrorType instead', E_USER_DEPRECATED);

