<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cast_channel.proto

namespace Cast_channel;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cast_channel.AuthResponse</code>
 */
class AuthResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes signature = 1;</code>
     */
    protected $signature = '';
    /**
     * Generated from protobuf field <code>bytes client_auth_certificate = 2;</code>
     */
    protected $client_auth_certificate = '';
    /**
     * Generated from protobuf field <code>repeated bytes client_ca = 3;</code>
     */
    private $client_ca;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $signature
     *     @type string $client_auth_certificate
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $client_ca
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CastChannel::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes signature = 1;</code>
     * @return string
     */
    public function getSignature()
    {
        return $this->signature;
    }

    /**
     * Generated from protobuf field <code>bytes signature = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkString($var, False);
        $this->signature = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes client_auth_certificate = 2;</code>
     * @return string
     */
    public function getClientAuthCertificate()
    {
        return $this->client_auth_certificate;
    }

    /**
     * Generated from protobuf field <code>bytes client_auth_certificate = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setClientAuthCertificate($var)
    {
        GPBUtil::checkString($var, False);
        $this->client_auth_certificate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes client_ca = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getClientCa()
    {
        return $this->client_ca;
    }

    /**
     * Generated from protobuf field <code>repeated bytes client_ca = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setClientCa($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->client_ca = $arr;

        return $this;
    }

}

