<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cast_channel.proto

namespace Cast_channel;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>cast_channel.AuthError</code>
 */
class AuthError extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.cast_channel.AuthError.ErrorType error_type = 1;</code>
     */
    protected $error_type = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $error_type
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CastChannel::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.cast_channel.AuthError.ErrorType error_type = 1;</code>
     * @return int
     */
    public function getErrorType()
    {
        return $this->error_type;
    }

    /**
     * Generated from protobuf field <code>.cast_channel.AuthError.ErrorType error_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setErrorType($var)
    {
        GPBUtil::checkEnum($var, \Cast_channel\AuthError\ErrorType::class);
        $this->error_type = $var;

        return $this;
    }

}

