<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cast_channel.proto

namespace Cast_channel;

if (false) {
    /**
     * This class is deprecated. Use Cast_channel\CastMessage\PayloadType instead.
     * @deprecated
     */
    class CastMessage_PayloadType {}
}
class_exists(CastMessage\PayloadType::class);
@trigger_error('Cast_channel\CastMessage_PayloadType is deprecated and will be removed in the next major release. Use Cast_channel\CastMessage\PayloadType instead', E_USER_DEPRECATED);

