<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cast_channel.proto

namespace Cast_channel;

if (false) {
    /**
     * This class is deprecated. Use Cast_channel\CastMessage\ProtocolVersion instead.
     * @deprecated
     */
    class CastMessage_ProtocolVersion {}
}
class_exists(CastMessage\ProtocolVersion::class);
@trigger_error('Cast_channel\CastMessage_ProtocolVersion is deprecated and will be removed in the next major release. Use Cast_channel\CastMessage\ProtocolVersion instead', E_USER_DEPRECATED);

